services:
  timescale:
    image: timescale/timescaledb:2.6.1-pg14
    container_name: "timescale"
    ports: 
      - 5432:5432
    volumes:
      - ./client_files/docker/timescale/initialize.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=thermostat
    networks:
      - gateway

  grafana:
    build:
      context: ./client_files/docker/grafana
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./client_files/docker/grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GRAFANA_DATA_HOST=timescale:5432
      - GF_INSTALL_PLUGINS=https://github.com/cloudspout/cloudspout-button-panel/releases/download/7.0.23/cloudspout-button-panel.zip;cloudspout-button-panel
    networks:
      - gateway

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80
    networks:
      - gateway

networks:
  gateway: